sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t khaled/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true khaled/docker-react npm run test


deploy:
  provider: elasticbeanstalk
  region: 'us-west-3'
  app: 'docker-react'
  env: 'Docker-react-env'
  bucket_name: 'elasticbeanstalk-eu-west-3-841402626865'
  bucket_path: 'docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
